version: '3.8'

services:
  app:
    build: .
    container_name: debtbook-app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/debtbook
      - DB_USERNAME=postgres
      - DB_PASSWORD=user
      - BOT_TOKEN=${BOT_TOKEN}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: debtbook-db
    environment:
      - POSTGRES_DB=debtbook
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=user
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
