server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/debtbook}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:user}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    resources:
      cache:
        period: 0

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: Asia/Tashkent
  telegram:
    bot:
      token: ${BOT_TOKEN:8484107475:AAF8ztaTnE8iJs-y5C8LBcEODTCxqZd_JMw}
  mail:
    username: ${MAIL_USERNAME:noreply@debtbook.com}
  mailgun:
    api-key: ${MAILGUN_API_KEY}
    domain: ${MAILGUN_DOMAIN}
eskiz:
  email: ${ESKIZ_EMAIL:musobek235@gmail.com}
  password: ${ESKIZ_PASSWORD:.Czp@#zC8pCcT3p}